import {scope} from './JS/scope.js'
import {loop} from './JS/loop.js'
import {closures} from './JS/closures.js'
import { callback } from './JS/callback.js'
import { prototype } from './JS/prototype.js'
